# see https://conda-forge.org/docs/maintainer/knowledge_base.html?#noarch-python
# for docs on providing multiple noarch platforms.
# see also this comment: https://github.com/conda-forge/devbio-napari-feedstock/pull/17#issuecomment-1249418027
target_os:
  - 'windows'  # [win]
  - 'linux'  # [linux]
  - 'osx'  # [osx]
