{% set name = "devbio-napari" %}
{% set version = "0.5.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/devbio-napari-{{ version }}.tar.gz
  sha256: b9fb04c32e2f13ede09287377bac9862ff265c0a4ad62a659ca574e896857683

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - napari <=0.4.15
    - napari-time-slicer
    - napari-workflows
    - napari-3d-ortho-viewer
    - napari-accelerated-pixel-and-object-classification
    - napari-animation
    - napari-brightness-contrast
    - napari-clusters-plotter
    - napari-crop
    - napari-curtain
    - napari-folder-browser
    - napari-layer-details-display
    - napari-plot-profile
    - napari-plugin-engine >=0.1.4
    - napari-plugin-search
    - napari-pyclesperanto-assistant
    - napari-segment-blobs-and-things-with-membranes
    - napari-simpleitk-image-processing
    - napari-skimage-regionprops
    - napari-tabu
    - napari-workflow-optimizer
    - napari-workflow-inspector
    - numpy >=1.21.4
    - platymatch
    - python >=3.7
    - redlionfish
    - napari-tools-menu
    - vispy <=0.9.6
    - napari-mouse-controls
    - napari-blob-detection
    - the-segmentation-game
    - jupyterlab
    - cellpose-napari

test:
  imports:
    - devbio_napari
  commands:
    - pip list
    # - pip check
  requires:
    - pip

about:
  home: https://github.com/haesleinhuepf/devbio-napari
  summary: A bundle of napari plugins useful for 3D+t image processing and analysis for studying developmental biology.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - haesleinhuepf
