{% set name = "devbio-napari" %}
{% set version = "0.5.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/devbio-napari-{{ version }}.tar.gz
  sha256: 84ae07d7ebb8f536c7a1b1451bcd87595725c40fbc90bec0fbccc0f57d0feee0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - napari-3d-ortho-viewer
    - napari-accelerated-pixel-and-object-classification
    - napari-animation
    - napari-brightness-contrast
    - napari-clusters-plotter
    - napari-crop
    - napari-curtain
    - napari-folder-browser
    - napari-layer-details-display
    - napari-plot-profile
    - napari-plugin-engine >=0.1.4
    - napari-plugin-search
    - napari-pyclesperanto-assistant
    - napari-segment-blobs-and-things-with-membranes
    - napari-simpleitk-image-processing
    - napari-skimage-regionprops
    - napari-tabu
    - napari-workflow-optimizer
    - napari-workflow-inspector
    - numpy >=1.21.4
    - platymatch
    - python >=3.7
    - redlionfish
    - napari-tools-menu
    - vispy <=0.9.6

test:
  imports:
    - devbio_napari
  commands:
    - pip list
    # - pip check
  requires:
    - pip

about:
  home: https://github.com/haesleinhuepf/devbio-napari
  summary: A bundle of napari plugins useful for 3D+t image processing and analysis for studying developmental biology.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/napari
    - haesleinhuepf
