{% set name = "devbio-napari" %}
{% set version = "0.11.0" %}
{% set build_number = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/devbio-napari-{{ version }}.tar.gz
  sha256: e25d826ad222c78b6e48cda98f4544c9cdaa563e48910c97b16282ee07b1a164

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: {{ build_number }}
  string: {{ noarch_platform }}_h{{ PKG_HASH }}_{{ build_number }}
  entry_points:
    - devbio-napari = devbio_napari:main

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - __{{ noarch_platform }}
    {% if noarch_platform == 'linux' %}
    - ocl-icd-system
    {% elif noarch_platform == 'osx' %}
    - ocl_icd_wrapper_apple
    {% endif %}
    - napari
    - napari-assistant >=0.4.9
    - napari-time-slicer
    - napari-workflows
    - napari-3d-ortho-viewer
    - napari-accelerated-pixel-and-object-classification
    - napari-animation
    - napari-brightness-contrast
    - napari-clusters-plotter >=0.7.1
    - napari-crop
    - napari-curtain
    - napari-folder-browser
    - napari-layer-details-display
    - napari-plot-profile
    - napari-plugin-engine >=0.1.4
    - npe2
    - napari-plugin-search
    - napari-pyclesperanto-assistant
    - napari-segment-blobs-and-things-with-membranes
    - napari-simpleitk-image-processing
    - napari-skimage-regionprops
    - napari-tabu
    - napari-workflow-optimizer
    - napari-workflow-inspector
    - numpy >=1.21.4
    - platymatch
    - python >={{ python_min }}
    - napari-tools-menu
    - vispy
    - napari-mouse-controls
    - napari-blob-detection
    - the-segmentation-game
    - jupyterlab
    - napari-czifile2
    - napari-roi
    - pydantic !=1.10.0
    - napari-pystackreg
    - imageio !=2.22.1
    - redlionfish
    - jupyter_server <2.0.0
    - libxml2 <=2.10.4
    - seaborn

test:
  imports:
    - devbio_napari
  commands:
    - pip list
    # - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/haesleinhuepf/devbio-napari
  summary: A bundle of napari plugins useful for 3D+t image processing and analysis for studying developmental biology.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - haesleinhuepf
