{% set name = "devbio-napari" %}
{% set version = "0.6.0" %}

# note that build number must be < 3 to avoid conflicts
# (see the build number calculation below)
{% set build_number = 1 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/devbio-napari-{{ version }}.tar.gz
  sha256: 12cc8bce8380473f7bd5c7faf083d88dc313cc961fa2bf3b9744fa0f785c714e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  {% if noarch_platform == 'linux' %}
  number: build_number
  {% endif %}
  {% else %}
  number: build_number
  {% if noarch_platform == 'osx' %}
  number: {{ build_number | int * 3 + 1 }}
  {% endif %}
  {% if noarch_platform == 'windows' %}
  number: {{ build_number | int * 3 + 2 }}
  {% endif %}

requirements:
  host:
    - pip
    - python >=3.8
  run:
    {% if noarch_platform == 'linux' %}
    - ocl-icd-system
    - __linux
    {% endif %}
    {% if noarch_platform == 'osx' %}
    - ocl_icd_wrapper_apple
    - __osx
    {% endif %}
    {% if noarch_platform == 'windows' %}
    - __win
    {% endif %}
    - napari <=0.4.15
    - napari-time-slicer
    - napari-workflows
    - napari-3d-ortho-viewer
    - napari-accelerated-pixel-and-object-classification
    - napari-animation
    - napari-brightness-contrast
    - napari-clusters-plotter
    - napari-crop
    - napari-curtain
    - napari-folder-browser
    - napari-layer-details-display
    - napari-plot-profile
    - napari-plugin-engine >=0.1.4
    - napari-plugin-search
    - napari-pyclesperanto-assistant
    - napari-segment-blobs-and-things-with-membranes
    - napari-simpleitk-image-processing
    - napari-skimage-regionprops
    - napari-tabu
    - napari-workflow-optimizer
    - napari-workflow-inspector
    - numpy >=1.21.4
    - platymatch
    - python >=3.8
    - redlionfish
    - napari-tools-menu
    - vispy <=0.9.6
    - napari-mouse-controls
    - napari-blob-detection
    - the-segmentation-game
    - jupyterlab
    - napari-czifile2
    - napari-roi
    - pydantic !=1.10.0
    - napari-pystackreg

test:
  imports:
    - devbio_napari
  commands:
    - pip list
    # - pip check
  requires:
    - pip

about:
  home: https://github.com/haesleinhuepf/devbio-napari
  summary: A bundle of napari plugins useful for 3D+t image processing and analysis for studying developmental biology.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - haesleinhuepf
